@baseUrl = http://localhost:3001

###
### USERS
###

// Создать пользователя
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "test4@example.com",
  "password": "1234567",
  "mustChangePassword": true,
  "role": "admin"
}

###
// Получить всех пользователей
GET {{baseUrl}}/users

###
// Получить пользователя по ID
GET {{baseUrl}}/users/1

###
// Обновить пользователя (пример: меняем пароль)
PATCH {{baseUrl}}/users/1
Content-Type: application/json

{
  "password": "new-password"
}

###
// Удалить пользователя
DELETE {{baseUrl}}/users/3


###
### ARTICLES
###

// Создать статью
POST {{baseUrl}}/articles
Content-Type: application/json

{
  "title": "My first article",
  "content": "Here is the content"
}

// Получить все статьи
GET {{baseUrl}}/articles

// Получить статью по ID
GET {{baseUrl}}/articles/1

// Обновить статью
PATCH {{baseUrl}}/articles/1
Content-Type: application/json

{
  "content": "Updated content"
}

// Удалить статью
DELETE {{baseUrl}}/articles/1


###
### TAGS
###

// Создать тег
POST {{baseUrl}}/tags
Content-Type: application/json

{
  "name": "NestJS"
}

// Получить все теги
GET {{baseUrl}}/tags

// Получить тег по ID
GET {{baseUrl}}/tags/1

// Обновить тег
PATCH {{baseUrl}}/tags/1
Content-Type: application/json

{
  "name": "Updated Tag"
}

// Удалить тег
DELETE {{baseUrl}}/tags/1


###
### PUBLISHERS
###

// Создать издателя
POST {{baseUrl}}/publisher
Content-Type: application/json

{
  "name": "Cool Publisher",
  "location": "New York"
}

// Получить всех издателей
GET {{baseUrl}}/publisher

// Получить издателя по ID
GET {{baseUrl}}/publisher/1

// Обновить издателя
PATCH {{baseUrl}}/publisher/1
Content-Type: application/json

{
  "location": "Los Angeles"
}

// Удалить издателя
DELETE {{baseUrl}}/publisher/1


###
### MAGAZINES
###

// Создать журнал
POST {{baseUrl}}/magazine
Content-Type: application/json

{
  "title": "My Great Magazine",
  "issueNumber": "Issue #1",
  "publisher": 1
}

// Получить все журналы
GET {{baseUrl}}/magazine

// Получить журнал по ID
GET {{baseUrl}}/magazine/1

// Обновить журнал
PATCH {{baseUrl}}/magazine/1
Content-Type: application/json

{
  "issueNumber": "Issue #2"
}

// Удалить журнал
DELETE {{baseUrl}}/magazine/1

